<%@ page import="password.pwm.config.PasswordStatus" %>
<%--
  ~ Password Management Servlets (PWM)
  ~ http://code.google.com/p/pwm/
  ~
  ~ Copyright (c) 2006-2009 Novell, Inc.
  ~ Copyright (c) 2009-2010 The PWM Project
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
  --%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ page language="java" session="true" isThreadSafe="true" contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="pwm" prefix="pwm" %>
<% final PasswordStatus passwordStatus = PwmSession.getPwmSession(session).getUserInfoBean().getPasswordState(); %>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<%@ include file="header.jsp" %>
<body onload="pwmPageLoadHandler(); startupChangePasswordPage(); getObject('password1').focus();">
<script type="text/javascript" src="<%=request.getContextPath()%>/resources/dojo/dojo/dojo.js" djConfig="parseOnLoad: false"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/resources/<pwm:url url='changepassword.js'/>"></script>
<div id="wrapper">
    <jsp:include page="header-body.jsp"><jsp:param name="pwm.PageName" value="Title_ChangePassword"/></jsp:include>
    <div id="centerbody">
        <% if (passwordStatus.isExpired() || passwordStatus.isPreExpired() || passwordStatus.isViolatesPolicy()) { %>
        <h1><pwm:Display key="Display_PasswordExpired"/></h1>
        <%-- <p/>You have <pwm:LdapValue name="loginGraceRemaining"/> remaining logins. --%>
        <% } %>
        <pwm:Display key="Display_ChangePassword"/>
        <div id="PasswordRequirements">
            <ul>
                <pwm:DisplayPasswordRequirements seperator="</li>" prepend="<li>"/>
            </ul>
        </div>
        <% final String passwordPolicyChangeMessage = PwmSession.getPwmSession(session).getUserInfoBean().getPasswordPolicy().getRuleHelper().getChangeMessage(); %>
        <% if (passwordPolicyChangeMessage.length() > 1 ) { %>
        <p><%= passwordPolicyChangeMessage %></p>
        <% } %>
        <%-- begin auto generate password [default is to not be visible, changepassword.js:startupPage() will make it visible]--%>
        <p id="autoGeneratePassword" style="visibility:hidden;">
            &nbsp;»&nbsp; <a href="javascript:fetchNewRandom();"><pwm:Display key="Display_AutoGeneratedPassword"/></a>
        </p>
        <%-- end auto generate password --%>
        <br/>

        <%  // if there is an error, then always show the error block if javascript is enabled.  Otherwise, mark the
            // error block as hidden, and if javascript is enabled, changepassword.js.startupPage() will make it visible
            if (PwmSession.getSessionStateBean(session).getSessionError() != null) {
        %>
        <span id="error_msg" class="msg-error"><pwm:ErrorMessage/></span>
        <% } else { %>
        <span style="visibility:hidden; background-color:#FFFFFF" id="error_msg" class="msg-success">&nbsp;</span>
        <% } %>

        <form action="<pwm:url url='ChangePassword'/>" method="post" enctype="application/x-www-form-urlencoded" onkeyup="validatePasswords();" onkeypress="checkForCapsLock(event);"
              onsubmit="handleChangePasswordSubmit(); handleFormSubmit('password_button');" name="changePassword">

            <table style="border:0">
                <tr>
                    <td style="border:0;" width="5%">
                        <h2><label for="password1"><pwm:Display key="Field_NewPassword"/></label></h2>
                        <input tabindex="1" type="password" name="password1" id="password1" class="inputfield"/>
                    </td>
                    <td style="border:0;" width="95%">
                        <%-- strength-meter [not shown initially, enabled by javascript; see also changepassword.js:markStrength() --%>
                        <div id="strengthBox" style="visibility:hidden;">
                            <div id="strengthLabel" style="padding-top:40px;"><pwm:Display key="Display_StrengthMeter"/></div>
                            <div class="progress-container" style="margin-bottom:10px">
                                <div id="strengthBar" style="width: 0">&nbsp;</div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="border:0;">
                        <h2><label for="password2"><pwm:Display key="Field_ConfirmPassword"/></label></h2>
                        <input tabindex="2" type="password" name="password2" id="password2" class="inputfield"/>
                    </td>
                    <td style="border:0;">
                        <%-- confirmation mark [not shown initially, enabled by javascript; see also changepassword.js:markConfirmationMark() --%>
                        <div style="padding-top:40px;">
                            <img style="visibility:hidden;" id="confirmCheckMark" alt="checkMark" height="15" width="15" src="<%=request.getContextPath()%>/resources/<pwm:url url='greenCheck.png'/>">
                            <img style="visibility:hidden;" id="confirmCrossMark" alt="crossMark" height="15" width="15" src="<%=request.getContextPath()%>/resources/<pwm:url url='redX.png'/>">
                        </div>
                    </td>
                </tr>
            </table>

            <div id="buttonbar" style="width:100%">
                <span>
                    <div id="capslockwarning" style="visibility:hidden;"><pwm:Display key="Display_CapsLockIsOn"/></div>
                </span>
                <input type="hidden" name="processAction" value="change"/>
                <input tabindex="3" type="submit" name="change" class="btn"
                       id="password_button"
                       value="    <pwm:Display key="Button_ChangePassword"/>    "/>
                <input tabindex="4" type="reset" name="reset" class="btn"
                       value="    <pwm:Display key="Button_Reset"/>    "
                       onclick="clearForm(); document.forms.changePassword.password1.focus();"/>
                <input type="hidden" name="hideButton" class="btn"
                       value="    <pwm:Display key="Button_Show"/>    "
                       onclick="toggleMaskPasswords();" id="hide_button"/>
                <input type="hidden" name="pwmFormID" id="pwmFormID"value="<pwm:FormID/>"/>
            </div>
        </form>
    </div>
    <br class="clear" />
</div>
<%-- hidden fields used by changepassword.js javascript display fields for i18n --%>
<form action="" name="hiddenForm">
    <input type="hidden" name="Js_Display_CheckingPassword" id="Js_Display_CheckingPassword" value="<pwm:Display key="Display_CheckingPassword"/>"/>
    <input type="hidden" name="Js_Display_PasswordChangedTo" id="Js_Display_PasswordChangedTo" value="<pwm:Display key="Display_PasswordChangedTo"/>"/>
    <input type="hidden" name="Js_Display_CommunicationError" id="Js_Display_CommunicationError" value="<pwm:Display key="Display_CommunicationError"/>"/>
    <input type="hidden" name="Js_Button_Hide" id="Js_Button_Hide" value="<pwm:Display key="Button_Hide"/>"/>
    <input type="hidden" name="Js_Button_Show" id="Js_Button_Show" value="<pwm:Display key="Button_Show"/>"/>
    <input type="hidden" name="Js_ChangePasswordURL" id="Js_ChangePasswordURL" value="<pwm:url url='ChangePassword'/>"/>
    <input type="hidden" name="Js_LeaveDirtyPasswordPage" id="Js_LeaveDirtyPasswordPage" value="<pwm:Display key="Display_LeaveDirtyPasswordPage"/>"/>
    <input type="hidden" name="Js_Strength_Low" id="Js_Strength_Low" value="<pwm:Display key="Display_PasswordStrengthLow"/>"/>
    <input type="hidden" name="Js_Strength_Medium" id="Js_Strength_Medium" value="<pwm:Display key="Display_PasswordStrengthMedium"/>"/>
    <input type="hidden" name="Js_Strength_High" id="Js_Strength_High" value="<pwm:Display key="Display_PasswordStrengthHigh"/>"/>
</form>
<%-- end hidden fields --%>
<%@ include file="footer.jsp" %>
</body>
</html>


