/*
 * Password Management Servlets (PWM)
 * http://www.pwm-project.org
 *
 * Copyright (c) 2006-2009 Novell, Inc.
 * Copyright (c) 2009-2021 The PWM Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package password.pwm.util.logging;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.UnsynchronizedAppenderBase;

public class LocalDBLogbackAppender extends UnsynchronizedAppenderBase<ILoggingEvent>
{
    private final LocalDBLogger localDBLogger;

    public LocalDBLogbackAppender( final LocalDBLogger localDBLogger )
    {
        this.localDBLogger = localDBLogger;
    }

    @Override
    protected void append( final ILoggingEvent event )
    {
        if ( PwmLogUtil.eventIsPwmGenerated( event ) )
        {
            // event was generated by PWM, which has already sent the event to the localDB
            return;
        }

        final PwmLogMessage logEvent = PwmLogMessage.fromLogbackEvent( event );
        localDBLogger.writeEvent( logEvent );
    }
}
