package password.pwm;

public enum PwmAboutProperty {

    app_version,
    app_chaiApiVersion,
    app_currentTime,
    app_startTime,
    app_installTime,
    app_currentPublishedVersion,
    app_currentPublishedVersionCheckTime,
    app_siteUrl,
    app_instanceID,
    app_wordlistSize,
    app_seedlistSize,
    app_sharedHistorySize,
    app_sharedHistoryOldestTime,
    app_emailQueueSize,
    app_emailQueueOldestTime,
    app_smsQueueSize,
    app_smsQueueOldestTime,
    app_syslogQueueSize,
    app_localDbLogSize,
    app_localDbLogOldestTime,
    app_localDbStorageSize,
    app_localDbFreeSpace,
    app_configurationRestartCounter,

    build_Time,
    build_Number,
    build_Type,
    build_User,
    build_Revision,
    build_JavaVendor,
    build_JavaVersion,
    build_Version,

    java_memoryFree,
    java_memoryAllocated,
    java_memoryMax,
    java_threadCount,
    java_vmVendor,
    java_vmLocation,
    java_vmVersion,
    java_runtimeVersion,
    java_vmName,
    java_osName,
    java_osVersion,
    java_randomAlgorithm,
}